apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster1
  region: ap-south-1
nodeGroups:
   - name: ng1
     instanceType: t2.micro
     desiredCapacity: 3
     ssh:
        publicKeyName: mykey4396
   - name: ng2
     desiredCapacity: 3
     instanceType: t2.small
     ssh:
        publicKeyName: mykey4396
